version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: vlrscraper
    networks:
      - vlr_scraper_net
    ports:
      - "8000:8000"
    env_file:
      - .env

networks:
  vlr_scraper_net:
    name: vlr_scraper_net
    driver: bridge